services:
  db:
    container_name: de_journal_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: engineer
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ride_share_warehouse
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: